Update deps to support project upgrades feature
subquery/subql-cosmos pull request #169
Opened 2023-08-29 03:25 UTC by stwiname

# Description
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have tested locally
- [ ] I have performed a self review of my changes
- [x] Updated any relevant documentation
- [x] Linked to any relevant issues
- [x] I have added tests relevant to my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] My code is up to date with the base branch
- [ ] I have updated relevant changelogs. [We suggest using chan](https://github.com/geut/chan/tree/main/packages/chan)

2023-09-28 23:10 UTC, stwiname reviewed
This commit needs to be applied https://github.com/subquery/subql/commit/296a8fa0eef30612ef676066381c71d9ceb63661

2023-09-28 23:10 UTC, stwiname commented on packages/node/package.json
> +    "@subql/types-core": "0.0.0-2",
```suggestion
```

2023-09-28 23:10 UTC, stwiname commented on packages/node/src/configure/configure.module.ts
> -    if (key === 'network-endpoint-param') {
Are we losing functionality here? I don't recall what these do?

2023-09-28 23:10 UTC, stwiname commented on packages/node/src/subcommands/reindex.module.ts
>      ReindexService,
Missing POIService. https://github.com/subquery/subql/commit/a60f85d6c2c16c74ea349d30710616cae097d7fb#diff-7006064ee2e455544671a4ce906c2f2b8dd794a20a41e0a2db5e9a5387fc3c9a

2023-09-28 23:10 UTC, stwiname commented on packages/types/src/project.ts
> +import {
This file is missing the JSDoc improvements

2023-10-02 23:17 UTC, jiqiang90 requested changes

2023-10-03 00:44 UTC, merged